### ISSUE TITLE
CSRF in Storybook

### ISSUE THREAD

**Issue by PascalPixel** [tai2/webpacker-react-example#10]
I need a CSRF token to retrieve data in some Components, but am unsure how to handle that in Storybook, as it is a separate instance of webpack.

It seems even `rails-ujs` just retrieves the token from a meta tag.

Any ideas or just use fake data for Storybook?

**Comment by tai2** [comment]
@Superpencil 

It looks weird to me that Storybook needs CSRF token.
Decoupling presentation and logic is a better way I think.
Storybook should be used for just presentation.

By the way, there may be some solutions for that situation.

* Send request for the app and scrape token from it.
* Add an abstraction layer for requests and mock it.
